CREATE TABLE museum_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    first_name TEXT,
    last_name TEXT,
    user_name TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    password TEXT NOT NULL
);
