CREATE TABLE museum_art_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    object_id INTEGER NOT NULL,
    primary_image TEXT NOT NULL,
    art_title TEXT NOT NULL,
    art_artist TEXT NOT NULL,
    art_date TEXT NOT NULL
);