CREATE TABLE users_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES museum_users(id) ON DELETE CASCADE NOT NULL,
    -- user_name TEXT REFERENCES museum_users(user_name) ON DELETE CASCADE,
    user_name TEXT REFERENCES museum_users(user_name) WHERE user_id EQUAL TO museum_users(id) ON DELETE CASCADE,
    -- objectID INTEGER REFERENCES museum_art_data(objectID) ON DELETE CASCADE NOT NULL,
    art_id INTEGER NOT NULL,
    comment TEXT NOT NULL
);