CREATE TABLE daily_interval (
    daily_interval_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id INTEGER NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    object_id INTEGER NOT NULL,
    primary_image TEXT NOT NULL,
    art_title TEXT NOT NULL,
    art_artist TEXT NOT NULL,
    art_date TEXT NOT NULL
);